crew_name: "Copy Crew"
usecase: "copy"
module_name: "copy"
output_filepath: "E:/Python/Amsha/.Amsha/output/intermediate/crew/crew_configurations.json"

crews:
  copy_crew:
#    knowledge_sources:
#      - "./docs/shared_project_guidelines.md"
#      - "./docs/style_guide.txt"
#    input:
#      source: "file"
#      path: "E:/Python/data/raw/features.json"
    steps:
      - task_key: "ad_copy_task"
        agent_key: "copywriter_agent"
#    knowledge_sources:
#      - "./data/market_research_summary.csv"
#      - "./data/competitor_analysis.pdf"
#      - "./data/user_feedback.txt"


pipeline:
  - "copy_crew"

