modules:
  crew_forge:
    status: completed
  crew_monitor:
    status: completed
  llm_factory:
    status: completed
  output_process:
    status: completed
cross_module:
  status: completed
final_report:
  status: completed
stats:
  total_modules: 4
